/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardAtom: typeof import('./src/components/CardAtom/CardAtom.vue')['default']
    CardGroup: typeof import('./src/components/CardGroup/CardGroup.vue')['default']
    CommonEmptyState: typeof import('./src/components/CommonEmptyState/CommonEmptyState.vue')['default']
    CommonSectionCard: typeof import('./src/components/CommonSectionCard/CommonSectionCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextEllipsis: typeof import('./src/components/TextEllipsis/TextEllipsis.vue')['default']
  }
}

// For TSX support
declare global {
  const CardAtom: typeof import('./src/components/CardAtom/CardAtom.vue')['default']
  const CardGroup: typeof import('./src/components/CardGroup/CardGroup.vue')['default']
  const CommonEmptyState: typeof import('./src/components/CommonEmptyState/CommonEmptyState.vue')['default']
  const CommonSectionCard: typeof import('./src/components/CommonSectionCard/CommonSectionCard.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TextEllipsis: typeof import('./src/components/TextEllipsis/TextEllipsis.vue')['default']
}